#include "waylandlayersurface.h"

/* Generated by wayland-scanner (see CMakeLists.txt) */
#include "wlr-layer-shell-unstable-v1-client-protocol.h"

#include <wayland-client.h>

#include <QGuiApplication>
#include <QScreen>
#include <QTimer>
#include <QtGui/qguiapplication_platform.h>

#include <sys/mman.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <fcntl.h>
#include <cstring>
#include <cerrno>

/*
 * Stub for xdg_popup_interface referenced by the layer-shell generated code
 * (get_popup opcode must stay in the XML for correct ack_configure numbering;
 * we never actually call it).
 */
extern "C" const struct wl_interface xdg_popup_interface = {
    "xdg_popup", 6, 0, nullptr, 0, nullptr
};

/* anonymous fd helper */

static int makeAnonFd(int size)
{
#ifdef __NR_memfd_create
    int fd = static_cast<int>(syscall(__NR_memfd_create, "layer-shm", 0));
    if (fd >= 0) {
        if (ftruncate(fd, size) == 0) return fd;
        close(fd);
    }
#endif
    char name[] = "/layer-shm-XXXXXX";
    {
        int rnd = open("/dev/urandom", O_RDONLY);
        if (rnd >= 0) {
            read(rnd, name + 12, 6);
            close(rnd);
            for (int i = 12; i < 18; ++i)
                name[i] = 'a' + (name[i] & 0xf);
        }
    }
    int sfd = shm_open(name, O_CREAT | O_RDWR | O_EXCL, 0600);
    if (sfd < 0) return -1;
    shm_unlink(name);
    if (ftruncate(sfd, size) < 0) { close(sfd); return -1; }
    return sfd;
}

/* WaylandLayerSurface */

WaylandLayerSurface::WaylandLayerSurface(QObject *parent) : QObject(parent) {}

WaylandLayerSurface::~WaylandLayerSurface()
{
    if (m_queueTimer) m_queueTimer->stop();
    destroyPool();
    if (m_layerSurf)  zwlr_layer_surface_v1_destroy(m_layerSurf);
    if (m_surface)    wl_surface_destroy(m_surface);
    if (m_layerShell) zwlr_layer_shell_v1_destroy(m_layerShell);
    if (m_compositor) wl_compositor_destroy(m_compositor);
    if (m_shm)        wl_shm_destroy(m_shm);
    if (m_queue)      wl_event_queue_destroy(m_queue);
}

bool WaylandLayerSurface::init(int width, int height, uint32_t anchor, Layer layer)
{
    m_width  = width;
    m_height = height;

    /* Device pixel ratio — used to allocate physical-pixel SHM buffers */
    QScreen *scr = QGuiApplication::primaryScreen();
    m_scale = scr ? static_cast<int>(scr->devicePixelRatio()) : 1;
    if (m_scale < 1) m_scale = 1;

    /* wl_display via Qt6 native interface */
    auto *wlApp = qGuiApp->nativeInterface<QNativeInterface::QWaylandApplication>();
    if (!wlApp) { qWarning("layer-shell: not a Wayland session"); return false; }

    m_display = wlApp->display();
    if (!m_display) { qWarning("layer-shell: wl_display is null"); return false; }

    /* Separate event queue */
    m_queue = wl_display_create_queue(m_display);

    auto *displayProxy = static_cast<wl_display *>(wl_proxy_create_wrapper(m_display));
    wl_proxy_set_queue(reinterpret_cast<wl_proxy *>(displayProxy), m_queue);

    /* Registry */
    static const wl_registry_listener regListener = { s_registryGlobal, s_registryRemove };
    auto *registry = wl_display_get_registry(displayProxy);
    wl_proxy_wrapper_destroy(reinterpret_cast<wl_proxy *>(displayProxy));
    wl_registry_add_listener(registry, &regListener, this);

    wl_display_roundtrip_queue(m_display, m_queue);
    wl_display_roundtrip_queue(m_display, m_queue);
    wl_registry_destroy(registry);

    if (!m_compositor || !m_shm || !m_layerShell) {
        qWarning("layer-shell: missing globals (compositor=%p shm=%p shell=%p)",
                 m_compositor, m_shm, m_layerShell);
        return false;
    }

    /* wl_surface + layer surface */
    m_surface = wl_compositor_create_surface(m_compositor);
    wl_proxy_set_queue(reinterpret_cast<wl_proxy *>(m_surface), m_queue);
    /* Tell the compositor our buffers are at m_scale× the logical size */
    wl_surface_set_buffer_scale(m_surface, m_scale);

    m_layerSurf = zwlr_layer_shell_v1_get_layer_surface(
        m_layerShell, m_surface, nullptr,
        static_cast<uint32_t>(layer), "popup");
    wl_proxy_set_queue(reinterpret_cast<wl_proxy *>(m_layerSurf), m_queue);

    static const zwlr_layer_surface_v1_listener lsListener = { s_lsConfigure, s_lsClosed };
    zwlr_layer_surface_v1_add_listener(m_layerSurf, &lsListener, this);

    /* Configure surface parameters — start with height=1 so compositor
     * gives us the configure event, then we hide immediately. */
    zwlr_layer_surface_v1_set_size(m_layerSurf, width, 1);
    zwlr_layer_surface_v1_set_anchor(m_layerSurf, anchor);
    zwlr_layer_surface_v1_set_exclusive_zone(m_layerSurf, 0);
    zwlr_layer_surface_v1_set_margin(m_layerSurf, 0, 0, 0, 0);
    zwlr_layer_surface_v1_set_keyboard_interactivity(m_layerSurf, 0);

    wl_surface_commit(m_surface);
    wl_display_roundtrip_queue(m_display, m_queue);

    if (!m_configured) {
        qWarning("layer-shell: no configure received");
        return false;
    }

    /* SHM pool at physical pixel size */
    if (!createPool(width * m_scale, height * m_scale))
        return false;

    /* Commit an initial transparent 1-px buffer so the surface is properly
     * mapped. We do NOT use null-attach because some compositors (niri) then
     * require a new configure-ack cycle before the next real buffer, which is
     * tricky to orchestrate reliably. A 1-px transparent buffer is invisible
     * and keeps the surface always-mapped with no protocol surprises. */
    hide();

    /* Integrate with Qt event loop — dispatch Wayland events at 8ms intervals.
     * wl_display_dispatch_queue_pending is non-blocking so it returns
     * immediately when there is nothing to process. */
    m_queueTimer = new QTimer(this);
    connect(m_queueTimer, &QTimer::timeout, this, &WaylandLayerSurface::dispatchQueue);
    m_queueTimer->start(8);

    return true;
}

/* Public API */

void WaylandLayerSurface::renderImage(const QImage &image)
{
    if (!m_configured || m_visibleHeight <= 0) return;

    const int visH     = qBound(1, m_visibleHeight, m_height);
    const int physW    = m_width  * m_scale;
    const int physVisH = visH     * m_scale;
    const int stride   = physW    * 4;

    /* Write physical-pixel rows to SHM */
    QImage src = image.convertToFormat(QImage::Format_ARGB32_Premultiplied);
    for (int y = 0; y < physVisH && y < src.height(); ++y)
        memcpy(m_data + y * stride, src.constScanLine(y),
               qMin(src.width(), physW) * 4);

    /* Buffer at physical size; set_size in logical pixels */
    auto *buf = wl_shm_pool_create_buffer(m_pool, 0, physW, physVisH,
                                           stride, WL_SHM_FORMAT_ARGB8888);
    static const wl_buffer_listener bl = {
        [](void *, wl_buffer *b) { wl_buffer_destroy(b); }
    };
    wl_buffer_add_listener(buf, &bl, nullptr);

    zwlr_layer_surface_v1_set_size(m_layerSurf, m_width, visH);  /* logical */

    wl_surface_attach(m_surface, buf, 0, 0);
    wl_surface_damage_buffer(m_surface, 0, 0, physW, physVisH);   /* physical */
    wl_surface_commit(m_surface);
    wl_display_flush(m_display);
}

void WaylandLayerSurface::hide()
{
    if (!m_surface || !m_configured || !m_pool) return;

    /* Use a transparent 1-px buffer — keeps the surface mapped so the
     * compositor never needs to send a new configure before the next real
     * buffer.  Explicitly zero the first row since renderImage may have
     * written non-transparent pixels there. */
    memset(m_data, 0, m_width * m_scale * 4);

    static const wl_buffer_listener bl = {
        [](void *, wl_buffer *b) { wl_buffer_destroy(b); }
    };
    auto *buf = wl_shm_pool_create_buffer(m_pool, 0,
                                           m_width * m_scale, 1,
                                           m_width * m_scale * 4, WL_SHM_FORMAT_ARGB8888);
    wl_buffer_add_listener(buf, &bl, nullptr);

    zwlr_layer_surface_v1_set_size(m_layerSurf, m_width, 1);
    wl_surface_attach(m_surface, buf, 0, 0);
    wl_surface_damage_buffer(m_surface, 0, 0, m_width * m_scale, 1);
    wl_surface_commit(m_surface);
    wl_display_flush(m_display);
    /* m_configured intentionally left true — surface stays mapped */
}

void WaylandLayerSurface::setVisibleHeight(int h)
{
    m_visibleHeight = h;
    /* Actual rendering is driven by PopupWidget::renderFrame() via
     * QPropertyAnimation::valueChanged → renderFrame() */
}

void WaylandLayerSurface::dispatchQueue()
{
    wl_display_dispatch_queue_pending(m_display, m_queue);
}

/* Registry callbacks */

void WaylandLayerSurface::s_registryGlobal(void *data, wl_registry *reg,
                                            uint32_t id, const char *iface,
                                            uint32_t version)
{
    auto *self = static_cast<WaylandLayerSurface *>(data);
    if (strcmp(iface, wl_compositor_interface.name) == 0)
        self->m_compositor = static_cast<wl_compositor *>(
            wl_registry_bind(reg, id, &wl_compositor_interface, qMin(version, 4u)));
    else if (strcmp(iface, wl_shm_interface.name) == 0)
        self->m_shm = static_cast<wl_shm *>(
            wl_registry_bind(reg, id, &wl_shm_interface, 1u));
    else if (strcmp(iface, zwlr_layer_shell_v1_interface.name) == 0)
        self->m_layerShell = static_cast<zwlr_layer_shell_v1 *>(
            wl_registry_bind(reg, id, &zwlr_layer_shell_v1_interface, qMin(version, 4u)));
}

void WaylandLayerSurface::s_registryRemove(void *, wl_registry *, uint32_t) {}

/* Layer surface callbacks */

void WaylandLayerSurface::s_lsConfigure(void *data, zwlr_layer_surface_v1 *surf,
                                         uint32_t serial, uint32_t w, uint32_t /*h*/)
{
    auto *self = static_cast<WaylandLayerSurface *>(data);
    zwlr_layer_surface_v1_ack_configure(surf, serial);
    /* Accept compositor's width (it knows the actual output width).
     * Do NOT update m_height — we manage height ourselves via visibleHeight. */
    if (w > 0) self->m_width = static_cast<int>(w);
    self->m_configured = true;
    emit self->configured(self->m_width, self->m_height);
}

void WaylandLayerSurface::s_lsClosed(void *data, zwlr_layer_surface_v1 *)
{
    static_cast<WaylandLayerSurface *>(data)->m_configured = false;
}

/* SHM pool */

bool WaylandLayerSurface::createPool(int width, int height)
{
    m_poolSz = width * height * 4;
    m_poolFd = makeAnonFd(m_poolSz);
    if (m_poolFd < 0) { qWarning("layer-shell: shm fd failed: %s", strerror(errno)); return false; }

    m_data = static_cast<uint8_t *>(
        mmap(nullptr, m_poolSz, PROT_READ | PROT_WRITE, MAP_SHARED, m_poolFd, 0));
    if (m_data == MAP_FAILED) {
        close(m_poolFd); m_poolFd = -1; m_data = nullptr;
        qWarning("layer-shell: mmap failed"); return false;
    }
    memset(m_data, 0, m_poolSz);

    m_pool = wl_shm_create_pool(m_shm, m_poolFd, m_poolSz);
    return m_pool != nullptr;
}

void WaylandLayerSurface::destroyPool()
{
    if (m_pool)  { wl_shm_pool_destroy(m_pool);    m_pool  = nullptr; }
    if (m_data)  { munmap(m_data, m_poolSz);        m_data  = nullptr; }
    if (m_poolFd >= 0) { close(m_poolFd);           m_poolFd = -1; }
}
